highlighter:       pygments

# Permalinks
permalink:           pretty

# Setup
title:               Jazz
tagline:             'Engineering Blog'
url:                 http://jazzco.github.io
paginate:            5

# About/contact
author:
  name:              The Jazz Engineering Team
  url:               http://jazzco.github.io
  email:             developers@jazz.co

# Custom vars
version:             1.0.0
