# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jazz Engineering Blog
tagline:             'Now 25% more AngularJS'
url:                 http://jazzco.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              The Jazz Engineering Team
  url:               http://jazzco.github.io
  email:             developers@jazz.co

# Custom vars
version:             1.0.0
